version: '0.5'

processes:
  setup:
    command: apps/email-list/scripts/setup_db.sh
    depends_on:
      mysql:
        condition: process_healthy
  email-dev:
    command: pnpm run --filter=email-list dev
